## NumPy Arrays

In [3]:
mlst = [1,2,3]
print(mlst)
print(type(mlst))

[1, 2, 3]
<class 'list'>


In [4]:
import numpy as np
ar = np.array(mlst)
print(ar)
print(type(ar))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
mtrx = [[1,2,3],[4,5,6],[7,8,9]] # it prints as List
print(mtrx)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [6]:
mat_ar =np.array(mtrx) # it prints in the form of matrix
print(mat_ar) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
a= np.arange(0,10)# it is using to give range
print("range between 0-10",a)
b= np.arange(0,10,2) # last value is step value
print("range between 0-10 with step value",b)

range between 0-10 [0 1 2 3 4 5 6 7 8 9]
range between 0-10 with step value [0 2 4 6 8]


In [12]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.linspace(0,5,5) # 1-dimensinal array

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [21]:
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.random.rand(4) # it prints random numbers

array([0.47486566, 0.38078358, 0.33728088, 0.14843221])

In [27]:
np.random.randn(2,3)

array([[-1.25903915, -0.40896449, -0.09741473],
       [ 0.08849328,  0.2095351 ,  1.91577397]])

In [32]:
np.random.randint(1,100) # it prints random integer value

94

In [34]:
np.random.randint(1,100,2) # last value represents how many numbers have to print

array([10, 68])

In [35]:
np.random.randint(1,100,10)

array([31, 30, 16, 39, 91, 19, 30, 77, 29, 60])

In [42]:
ar = np.arange(25)
print(ar)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [45]:
arr = np.random.randint(0,50,10)
print(arr)

[39 11 47 42 29 44  7 24 36 13]


In [43]:
ar.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
print(arr)

[39 11 47 42 29 44  7 24 36 13]


In [49]:
arr.max() #it prints  max value

47

In [50]:
arr.min() # it prints min value

7

In [51]:
arr.argmax() # it shows the index value of max valu

2

In [52]:
arr.argmin() # it shows the index value of min value

6

In [53]:
arr.shape # it shows no. of values in 'arr' 

(10,)

In [54]:
ar.shape

(25,)

In [58]:
ar= ar.reshape(5,5)
print(ar)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [59]:
ar.shape

(5, 5)

In [62]:
ar.dtype

dtype('int32')

## NumPy Indexing and Selection

In [64]:
import numpy as np
a = np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])