# Turtle graphs

In [10]:
# design spiral star
import turtle as t
a= t.Turtle()
a.pencolor('red')
for i in range(40):
    a.forward(i * 10)
    a.left(144)
t.done()    

In [1]:
# design square
import turtle as t
a= t.Turtle()
for i in range(40):
    a.forward(i)
    a.left(90)
t.done()    

In [ ]:
# design spiral square
import turtle as t
a= t.Turtle()
for i in range(50):
    a.forward(i)
    a.left(92)
t.done()    

## Pandas and Marplotlib

In [10]:
import pandas as pd
df = pd.read_csv('deliveries.csv')
print(df)

        match_id  inning         batting_team                 bowling_team  \
0              1       1  Sunrisers Hyderabad  Royal Challengers Bangalore   
1              1       1  Sunrisers Hyderabad  Royal Challengers Bangalore   
2              1       1  Sunrisers Hyderabad  Royal Challengers Bangalore   
3              1       1  Sunrisers Hyderabad  Royal Challengers Bangalore   
4              1       1  Sunrisers Hyderabad  Royal Challengers Bangalore   
...          ...     ...                  ...                          ...   
179073     11415       2  Chennai Super Kings               Mumbai Indians   
179074     11415       2  Chennai Super Kings               Mumbai Indians   
179075     11415       2  Chennai Super Kings               Mumbai Indians   
179076     11415       2  Chennai Super Kings               Mumbai Indians   
179077     11415       2  Chennai Super Kings               Mumbai Indians   

        over  ball    batsman non_striker      bowler  is_super

## Groupby

In [11]:
import pandas as pd
df.columns.tolist()

['match_id',
 'inning',
 'batting_team',
 'bowling_team',
 'over',
 'ball',
 'batsman',
 'non_striker',
 'bowler',
 'is_super_over',
 'wide_runs',
 'bye_runs',
 'legbye_runs',
 'noball_runs',
 'penalty_runs',
 'batsman_runs',
 'extra_runs',
 'total_runs',
 'player_dismissed',
 'dismissal_kind',
 'fielder']

In [12]:
df.groupby('bowler')['wide_runs'].mean().head()

bowler
A Ashish Reddy    0.029630
A Chandila        0.000000
A Choudhary       0.055556
A Dananjaya       0.040000
A Flintoff        0.000000
Name: wide_runs, dtype: float64

In [13]:
df.groupby('match_id')['player_dismissed'].head()

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ... 
178830    NaN
178831    NaN
178832    NaN
178833    NaN
178834    NaN
Name: player_dismissed, Length: 3780, dtype: object

In [14]:
df.groupby('match_id')['ball'].mean().head() 
#head is using for to know first few records 

match_id
1    3.658228
2    3.603239
3    3.637615
4    3.708502
5    3.616935
Name: ball, dtype: float64

In [15]:
df.groupby('match_id')['ball'].mean().tail()
# tail is using for to know last few records

match_id
11347    3.675439
11412    3.573840
11413    3.690476
11414    3.573222
11415    3.608871
Name: ball, dtype: float64

In [ ]:
# where clause to select statement
# Group by clause

## Data Cleaning
   - whenever you have a lot of missing records values in the given dataset then you can isnull()
   - isnull() will notify the any missing values in the dataframe.  

In [16]:
df.isnull()

match_id  inning  batting_team  bowling_team   over   ball  batsman  \
0          False   False         False         False  False  False    False   
1          False   False         False         False  False  False    False   
2          False   False         False         False  False   True    False   
3          False   False         False         False   True  False    False   
4          False   False         False         False  False  False    False   
...          ...     ...           ...           ...    ...    ...      ...   
179073     False   False         False         False  False  False    False   
179074     False   False         False         False  False  False    False   
179075     False   False         False         False  False  False    False   
179076     False   False         False         False  False  False    False   
179077     False   False         False         False  False  False    False   

        non_striker  bowler  is_super_over  ...  bye_runs  legbye_runs  \
0             False   False          False  ...     False        False   
1             False   False          False  ...     False        False   
2             False   False          False  ...     False        False   
3             False   False          False  ...     False        False   
4             False   False          False  ...     False        False   
...             ...     ...            ...  ...       ...          ...   
179073        False   False          False  ...     False        False   
179074        False   False          False  ...     False        False   
179075        False   False          False  ...     False        False   
179076        False   False          False  ...     False        False   
179077        False   False          False  ...     False        False   

        noball_runs  penalty_runs  batsman_runs  extra_runs  total_runs  \
0             False         False         False       False       False   
1             False         False         False       False       False   
2             False         False         False       False       False   
3             False         False         False       False       False   
4             False         False         False       False       False   
...             ...           ...           ...         ...         ...   
179073        False         False         False       False       False   
179074        False         False         False       False       False   
179075        False         False         False       False       False   
179076        False         False         False       False       False   
179077        False         False         False       False       False   

        player_dismissed  dismissal_kind  fielder  
0                   True            True     True  
1                   True            True     True  
2                   True            True     True  
3                   True            True     True  
4                   True            True     True  
...                  ...             ...      ...  
179073              True            True     True  
179074              True            True     True  
179075             False           False    False  
179076              True            True     True  
179077             False           False     True  

[179078 rows x 21 columns]

In [17]:
# Entire data set
df.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                    10
ball                    11
batsman                  0
non_striker              0
bowler                   0
is_super_over            0
wide_runs                0
bye_runs                 0
legbye_runs              0
noball_runs              0
penalty_runs             0
batsman_runs             0
extra_runs               0
total_runs               0
player_dismissed    170244
dismissal_kind      170244
fielder             172630
dtype: int64

In [18]:
# Only one colomn data set
df['bowler'].isnull().sum()

0

- **dropna()** This function allows you to drop all or sme rows that have missing values
- **fillna()** This function allows you to replace the rows that have missing values with the value what want pass

In [19]:
len(df)

179078

In [21]:
# Droping rows with 1 null value
new_df = df.dropna(axis=0,how='any')

In [22]:
len(new_df)

6448

In [23]:
df

match_id  inning         batting_team                 bowling_team  \
0              1       1  Sunrisers Hyderabad  Royal Challengers Bangalore   
1              1       1  Sunrisers Hyderabad  Royal Challengers Bangalore   
2              1       1  Sunrisers Hyderabad  Royal Challengers Bangalore   
3              1       1  Sunrisers Hyderabad  Royal Challengers Bangalore   
4              1       1  Sunrisers Hyderabad  Royal Challengers Bangalore   
...          ...     ...                  ...                          ...   
179073     11415       2  Chennai Super Kings               Mumbai Indians   
179074     11415       2  Chennai Super Kings               Mumbai Indians   
179075     11415       2  Chennai Super Kings               Mumbai Indians   
179076     11415       2  Chennai Super Kings               Mumbai Indians   
179077     11415       2  Chennai Super Kings               Mumbai Indians   

        over  ball    batsman non_striker      bowler  is_super_over  ...  \
0        1.0   1.0  DA Warner    S Dhawan    TS Mills              0  ...   
1        1.0   2.0  DA Warner    S Dhawan    TS Mills              0  ...   
2        1.0   NaN  DA Warner    S Dhawan    TS Mills              0  ...   
3        NaN   4.0  DA Warner    S Dhawan    TS Mills              0  ...   
4        1.0   5.0  DA Warner    S Dhawan    TS Mills              0  ...   
...      ...   ...        ...         ...         ...            ...  ...   
179073  20.0   2.0  RA Jadeja   SR Watson  SL Malinga              0  ...   
179074  20.0   3.0  SR Watson   RA Jadeja  SL Malinga              0  ...   
179075  20.0   4.0  SR Watson   RA Jadeja  SL Malinga              0  ...   
179076  20.0   5.0  SN Thakur   RA Jadeja  SL Malinga              0  ...   
179077  20.0   6.0  SN Thakur   RA Jadeja  SL Malinga              0  ...   

        bye_runs  legbye_runs  noball_runs  penalty_runs  batsman_runs  \
0              0            0            0             0             0   
1              0            0            0             0             0   
2              0            0            0             0             4   
3              0            0            0             0             0   
4              0            0            0             0             0   
...          ...          ...          ...           ...           ...   
179073         0            0            0             0             1   
179074         0            0            0             0             2   
179075         0            0            0             0             1   
179076         0            0            0             0             2   
179077         0            0            0             0             0   

        extra_runs  total_runs  player_dismissed dismissal_kind    fielder  
0                0           0               NaN            NaN        NaN  
1                0           0               NaN            NaN        NaN  
2                0           4               NaN            NaN        NaN  
3                0           0               NaN            NaN        NaN  
4                2           2               NaN            NaN        NaN  
...            ...         ...               ...            ...        ...  
179073           0           1               NaN            NaN        NaN  
179074           0           2               NaN            NaN        NaN  
179075           0           1         SR Watson        run out  KH Pandya  
179076           0           2               NaN            NaN        NaN  
179077           0           0         SN Thakur            lbw        NaN  

[179078 rows x 21 columns]

In [25]:
df['match_id'].fillna('Testing',inplace= True)

In [26]:
df

match_id  inning         batting_team                 bowling_team  \
0              1       1  Sunrisers Hyderabad  Royal Challengers Bangalore   
1              1       1  Sunrisers Hyderabad  Royal Challengers Bangalore   
2              1       1  Sunrisers Hyderabad  Royal Challengers Bangalore   
3              1       1  Sunrisers Hyderabad  Royal Challengers Bangalore   
4              1       1  Sunrisers Hyderabad  Royal Challengers Bangalore   
...          ...     ...                  ...                          ...   
179073     11415       2  Chennai Super Kings               Mumbai Indians   
179074     11415       2  Chennai Super Kings               Mumbai Indians   
179075     11415       2  Chennai Super Kings               Mumbai Indians   
179076     11415       2  Chennai Super Kings               Mumbai Indians   
179077     11415       2  Chennai Super Kings               Mumbai Indians   

        over  ball    batsman non_striker      bowler  is_super_over  ...  \
0        1.0   1.0  DA Warner    S Dhawan    TS Mills              0  ...   
1        1.0   2.0  DA Warner    S Dhawan    TS Mills              0  ...   
2        1.0   NaN  DA Warner    S Dhawan    TS Mills              0  ...   
3        NaN   4.0  DA Warner    S Dhawan    TS Mills              0  ...   
4        1.0   5.0  DA Warner    S Dhawan    TS Mills              0  ...   
...      ...   ...        ...         ...         ...            ...  ...   
179073  20.0   2.0  RA Jadeja   SR Watson  SL Malinga              0  ...   
179074  20.0   3.0  SR Watson   RA Jadeja  SL Malinga              0  ...   
179075  20.0   4.0  SR Watson   RA Jadeja  SL Malinga              0  ...   
179076  20.0   5.0  SN Thakur   RA Jadeja  SL Malinga              0  ...   
179077  20.0   6.0  SN Thakur   RA Jadeja  SL Malinga              0  ...   

        bye_runs  legbye_runs  noball_runs  penalty_runs  batsman_runs  \
0              0            0            0             0             0   
1              0            0            0             0             0   
2              0            0            0             0             4   
3              0            0            0             0             0   
4              0            0            0             0             0   
...          ...          ...          ...           ...           ...   
179073         0            0            0             0             1   
179074         0            0            0             0             2   
179075         0            0            0             0             1   
179076         0            0            0             0             2   
179077         0            0            0             0             0   

        extra_runs  total_runs  player_dismissed dismissal_kind    fielder  
0                0           0               NaN            NaN        NaN  
1                0           0               NaN            NaN        NaN  
2                0           4               NaN            NaN        NaN  
3                0           0               NaN            NaN        NaN  
4                2           2               NaN            NaN        NaN  
...            ...         ...               ...            ...        ...  
179073           0           1               NaN            NaN        NaN  
179074           0           2               NaN            NaN        NaN  
179075           0           1         SR Watson        run out  KH Pandya  
179076           0           2               NaN            NaN        NaN  
179077           0           0         SN Thakur            lbw        NaN  

[179078 rows x 21 columns]

## NumPy Library
   - Processing of N-dimensional arays
   - NumPy is an open souce library available in pyhton
   - This is used for Math, Scientific, data science programming 

In [31]:
import numpy as np
li = [1,2,3,4,5,6,7,8]
a= np.array(li)# convert list to array by using numpy
print(a)
print(type(a))

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


In [32]:
print(a.shape)# shape is used to konw how many columns are there

(8,)


In [33]:
print(a.dtype)

int32


In [34]:
# Two-Dimentional array
b= np.array([(1,2,3),(4,5,6)])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
print(b.shape)
print(a.dtype)

(2, 3)
int32


### np.zeros() and np.ones()
   - To initialize the weight during the first iteration of TensorFlow

In [38]:
x= np.zeros((2,2)) # dtype as float
print(x)

[[0. 0.]
 [0. 0.]]


In [42]:
x= np.zeros((2,2),dtype=np.int)
print(x)

[[0 0]
 [0 0]]


In [43]:
x= np.ones((2,2))

In [ ]:
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\''''''\''